  on:
    push:
      branches:
        - master





  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: action/checkout@v3

        - name: "Login to Docker"
          run: docker login --username khaled8 --password dckr_pat_Bcdf7oMG9ZCCZhy60VGdEVb-snY
           
